site_name: Serendipity
docs_dir: docs # Tell MkDocs to look in the 'docs/' folder for Markdown files

theme:
  name: material
  features:
    - navigation.tabs
    - toggle.dark_mode
    - navigation.footer # Enables dark mode toggle (required for the toggle to appear)
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom
      accent: custom
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - awesome-pages

use_directory_urls: false

nav:
  - Home: index.md

  - Serendipity:
      - Accounts:
          - Kaas user Guide:
              - Kaas MainSheet Summary: serendipitydoc/accounts/kaasuserguide/KaasMainSheetSummary.md
              - Kaas Sheet Header Indexes: serendipitydoc/accounts/kaasuserguide/KaasSheetHeaderDescription.md
              - Kaas Sheets Summary: serendipitydoc/accounts/kaasuserguide/KaasSheetsSummary.md
          - Accounting Guide:
              - Account Daily Report: serendipitydoc/accounts/accountingguide/AccountDailyReport.md
              - Account Standard Operating Procedures: serendipitydoc/accounts/accountingguide/AccountStandardOperatingProcedures.md
              - Account Transaction Scenarios: serendipitydoc/accounts/accountingguide/AccountTransactionScenarios.md
              - AccQT Prd: serendipitydoc/accounts/accountingguide/AccQTPrd.md
              - Serendipity Business Requirements Plan: serendipitydoc/accounts/accountingguide/SerendipityBusinessRequirementsPlan.md
      - HR Onboarding Library:
          - Employee Onboarding Guide: serendipitydoc/hronboardinglibrary/EmployeeOnboardingGuide.md
      - General Guidelines:
          - File Naming Guidelines: serendipitydoc/generalguidelines/FileNamingGuidelines.md
          - Audio Meeting Guidelines: serendipitydoc/generalguidelines/AudioMeetingGuidelines.md
          - DUNS Registration formalities: serendipitydoc/generalguidelines/DUNSRegFormalities.md

  - TradeMan:
      - Projects:
          - TradeManV1:
              - Onboarding Guide: trademandoc/Projects/trademanV1/OnboardingGuide.md
              - TradeManV1 Meetings: trademandoc/Projects/trademanV1/TradeManMeetingAudio_Transcribe.md
          - HakunaMatata:
              - HakunaMatata Dev Guide: trademandoc/Projects/hakunamatata/HakunaMatataDevGuide.md
          - Kaas:
              - Kaas App Prompt: trademandoc/Projects/kaas/KaasAppPrompt.md
              - Fabric Kaas: trademandoc/Projects/kaas/FabricKaas.md
          - ChitBox:
              - API Sethu and Distributed Ledger Technology:
                  - API sethu documentation: trademandoc/Projects/chitbox/apisethudocs/ApiSethuDocs.md
                  - DLT Implementation Guide: trademandoc/Projects/chitbox/apisethudocs/DLTImplementationGuide.md
                  - DLT Entity Registration: trademandoc/Projects/chitbox/apisethudocs/DLTEntityRegistration.md
                  - DLT Header Manual Ping: trademandoc/Projects/chitbox/apisethudocs/DLTHeaderManualPing.md
                  - DLT Content Approval: trademandoc/Projects/chitbox/apisethudocs/DLTContentApproval.md

              - App Design Technical Documentation: trademandoc/Projects/chitbox/AppDesignTechnicalDocs.md
              - System Design (LLD+HLD): trademandoc/Projects/chitbox/SystemDesignLLD_HLD.md

      - Tech Guidelines:
          - GitHub Repositories: trademandoc/tech_guidelines/GitHubRepos.md
          - Commit Convention Guideline: trademandoc/tech_guidelines/CommitConventionGuideline.md
          - Agent Creation Guidelines: trademandoc/tech_guidelines/AgentCreationGuideline.md
          - RBAC Guidelines: trademandoc/tech_guidelines/RbacGuidelines.md
          - Prompt Collection: trademandoc/tech_guidelines/PromptCollections.md
      - Software Instructions:
          - Coolify Phase1: trademandoc/software_instructions/CoolifyBeginPhase1.md
          - Coolify Instructions: trademandoc/software_instructions/CoolifyInstructions.md
          - Cloudflare Hosting: trademandoc/software_instructions/CloudflareHosting.md
          - Jio Router Config: trademandoc/software_instructions/JioRouterConfig.md
          - Payment Gateway Benefits Razorpay: trademandoc/software_instructions/PaymentGatewayBenefits.md
      - Reports:
          - Tech Daily Report: trademandoc/reports/TechDailyReport.md
          - Development Schedule: trademandoc/reports/DevelopmentSch.md

  - DhoomStudios:
      - Debt Reference: dhoomstudiosdoc/DebtReference.md
      - Debt Reviewed: dhoomstudiosdoc/DebtReviewed.md
      - Adobe Creative Suite: dhoomstudiosdoc/AdobeCreativeSuite.md
      - Script Guide: dhoomstudiosdoc/ScriptGuide.md
      - Old Man's Tale: dhoomstudiosdoc/OldMansTale.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Serendipity2-0
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/trademanv1?s=21&t=bBTay4-vvjkbqF5YnSYrog
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/trademan.v1?igsh=NnZ6dDR2M2Nhc3h5
    - icon: fontawesome/solid/envelope
      link: mailto:your-email@example.com # Replace with your actual email

  # Including media folder so audio can be served properly
  include:
    - media/

extra_css:
  - css/custom.css
