site_name: Serendipity
docs_dir: docs # Tell MkDocs to look in the 'docs/' folder for Markdown files

theme:
  name: material
  features:
    - navigation.tabs
    - toggle.dark_mode
    - navigation.footer  # Enables dark mode toggle (required for the toggle to appear)
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom
      accent: custom
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - awesome-pages

use_directory_urls: false  

nav:
  - Home: index.md

  - Serendipity:
      - AccQT Prd: serendipitydoc/AccQTPrd.md
      - Account Daily Report: serendipitydoc/AccountDailyReport.md
      - Audio Meeting Guidelines: serendipitydoc/AudioMeetingGuidelines.md
      - File Naming Guidelines: serendipitydoc/FileNamingGuidelines.md
      - Kaas Main Sheet Summary: serendipitydoc/KaasMainSheetSummary.md
      - Kaas Sheets Summary: serendipitydoc/KaasSheetsSummary.md
      - Script Guide: serendipitydoc/ScriptGuide.md
      - Prompt Collections: serendipitydoc/PromptCollections.md
      - Employee OnboardingGuide: serendipitydoc/EmployeeOnboardingGuide.md
      - Kaas Sheet Header Description: serendipitydoc/KaasSheetHeaderDescription.md
      - Account Transaction Scenarios: serendipitydoc/AccountTransactionScenarios.md
      - Account Standard Operating Procedures: serendipitydoc/AccountStandardOperatingProcedures.md

  - TradeMan:
      - Projects:
          - TradeManV1:
              - Onboarding Guide: trademandoc/Projects/trademanV1/OnboardingGuide.md
              - TradeManV1 Meetings: trademandoc/Projects/trademanV1/TradeManMeetingAudio_Transcribe.md
          - HakunaMatata:
              - HakunaMatata Dev Guide: trademandoc/Projects/hakunamatata/HakunaMatataDevGuide.md
          - Kaas:
              - Kaas App Prompt: trademandoc/Projects/kaas/KaasAppPrompt.md
              - Fabric Kaas: trademandoc/Projects/kaas/FabricKaas.md
              
      - Tech Guidelines:
          - Commit Convention Guideline: trademandoc/tech_guidelines/CommitConventionGuideline.md
          - Agent Creation Guidelines: trademandoc/tech_guidelines/AgentCreationGuideline.md
          - RBAC Guidelines: trademandoc/tech_guidelines/RbacGuidelines.md
      - Software Instructions:
          - Coolify Phase1: trademandoc/software_instructions/CoolifyBeginPhase1.md
          - Coolify Instructions: trademandoc/software_instructions/CoolifyInstructions.md
      - Reports:
          - Tech Daily Report: trademandoc/reports/TechDailyReport.md
          - Development Schedule: trademandoc/reports/developmentSch.MD

  - DhoomStudios:
      - Debt Reference: dhoomstudiosdoc/DebtReference.md
      - Debt Reviewed: dhoomstudiosdoc/DebtReviewed.md
      - Jio Router Config: dhoomstudiosdoc/JioRouterConfig.md
      - Adobe Creative Suite: dhoomstudiosdoc/AdobeCreativeSuite.md
      - Old Man's Tale: dhoomstudiosdoc/OldMansTale.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Serendipity2-0
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/trademanv1?s=21&t=bBTay4-vvjkbqF5YnSYrog
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/trademan.v1?igsh=NnZ6dDR2M2Nhc3h5
    - icon: fontawesome/solid/envelope
      link: mailto:your-email@example.com # Replace with your actual email

  # Including media folder so audio can be served properly
  include:
    - media/

extra_css:
  - css/custom.css
