name: GitHub Pages CI

on:
  push:
    branches:
      - branch/hakuna-matata_docs # The branch that triggers the workflow

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Install MkDocs and required plugins
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin

      # Build and deploy the documentation
      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
